dbt_post_2:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: dbt-2
      schema: raw_data
      threads: 4
  target: dev
